## Logistic Regression Workshop

In [12]:
import numpy as np
import pandas as pd

df = pd.read_csv('iris-data-clean.csv')
df['class'] = df['class'].replace({
    'Setosa': 0,
    'Virginica': 1,
    'Versicolor': 2
})

from sklearn import linear_model
from sklearn.model_selection import train_test_split

x = df[['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'petal_width_cm']]
y = df['class']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train, y_train)

print(model.predict([[4, 3, 2, 0.5]]))

print(model.coef_)
print(model.intercept_)

y_pred = model.predict(x_test)


[0]
[[-0.4096163   0.89406736 -2.38141014 -1.00919054]
 [ 0.04697952 -0.54286389  2.61086706  1.80118774]
 [ 0.36263679 -0.35120347 -0.22945692 -0.79199719]]
[  9.47741796 -12.62287305   3.14545508]


/tmp/ipykernel_46219/4079796338.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['class'] = df['class'].replace({
/home/codespace/.local/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [13]:
import numpy as np
import pandas as pd

df = pd.read_csv('iris-data-clean.csv')
df['class'] = df['class'].replace({
    'Setosa': 0,
    'Virginica': 1,
    'Versicolor': 2
})

from sklearn import linear_model
from sklearn.model_selection import train_test_split

x = df[['sepal_length_cm', 'sepal_width_cm']]
y = df['class']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train, y_train)

print(model.predict([[4, 3]]))

print(model.coef_)
print(model.intercept_)

y_pred = model.predict(x_test)


[0]
[[-2.50323     2.15948694]
 [ 2.07635805 -0.55904214]
 [ 0.42687195 -1.6004448 ]]
[  7.27150556 -10.27747664   3.00597108]


/tmp/ipykernel_46219/2787497043.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['class'] = df['class'].replace({
/home/codespace/.local/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
